### ISSUE TITLE
Using only one python environment for the benchmark

### ISSUE THREAD

**Issue by NathanMolinier** [spinalcordtoolbox/disc-labeling-benchmark#2]
## Description

Using a single environment to handle multiple imported methods is tricky and sometimes impossible.

## Current state

For now, environment conflicts are not too important and it is possible to use the [spinalcordtoolbox](https://github.com/spinalcordtoolbox/spinalcordtoolbox), the [hourglass](https://github.com/spinalcordtoolbox/disc-labeling-hourglass) network and the [spinenet](https://github.com/rwindsor1/SpineNet) network in a single environment.

This issue is meant to discuss potential future `hard` conflicts

**Comment by jcohenadad** [comment]
I don't think this is the right approach-- it is OK to have independent methods being run by a SHELL script, without being constrainted inside a single venv. Eg: you could have executables, etc. and the only goal of this benchmark script is to run each method on the same dataset.

**Comment by NathanMolinier** [comment]
The benchmark script also has its own packages and requirements. Installing these packages will therefore be needed in the different environments.
